### ISSUE TITLE
OmniSharp Agenda » Meeting Thursday January 26th, 2017 @ 18:00 UTC

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/OmniSharp#15]
| PST (UTC-8) | EST (UTC-5) | London (UTC) | Zürich (UTC+2) | Helsinki (UTC+3) | Sydney (UTC+10) |
| --- | --- | --- | --- | --- | --- |
| 11:00 AM | 2:00 PM | 6:00 PM | 8:00 PM | 9:00 PM | 4:00 AM |
## Meeting info

[Join skype meeting](https://meet.lync.com/microsoft/sayedha/ZP85BD81)

Join by Phone
Toll-free number: +1 (866) 641-7188 or Toll number: +1 (773) 917-4061 
[Find a local number](https://dialin.lync.com/microsoft.com/sayedha)

Conference ID: 280856 

[Help](https://support.office.com/en-us/article/Skype-for-Business-meeting-help-e0bc00a0-b01f-4f51-88fa-6f74abefa203?ui=en-US&rs=en-US&ad=US)
## Agenda

If you can think of any more agenda items, feel free to edit the issue (if you have permissions) or just comment on this thread and we'll make sure to group them up before the meeting.

Also feel free to discuss any agenda items early as part of this issue, we can make sure to recap during the start of the meeting, and may cut down on the time we have to spend on some of them.

### Razor

I've started to dive into what it takes to get Razor up and running inside OmniSharp.  After weekends prototype I was able to successfully get diagnostics back from Razor in my unit tests.  That's the first step toward glory!

Have not messed with the proof of concept too much lately, will re-evaluate once MSBuild changes land and stabilize.

Code is at:
https://github.com/OmniSharp/omnisharp-roslyn/tree/razorhost
### Project Management
Github has a decent project broad system that needs some invesitgation, I never fully set up the Huboard system, so this might be a good replacement.

### Telemetry

No updates yet, see #5 for details.

### Project Che Integration

http://www.eclipse.org/che/

### New Project System

@DustinCampbell has brought in a ton of work that brings in the new CLI / MSBuild project support, after Summit there was a lot of things I liked.

### OmniSharp-atom
- Trying to find time to sit and solve the issues surrounding this... I have a new computer, so it'll be easier to handle.  The other weekend I tried, my computer decided it didn't want to work on it, and I gave up.
- Some problems are left unresolved.

### Atom-LangaugeClient
- I'm work on a replacement that brings the language server to Atom...
- https://github.com/OmniSharp/atom-languageclient
- The goal is to get this up to the feature support of OmniSharp-Atom, and then work on UI / Stability before major movements.
- The atom team has reached out for some information, so there may be some more moment behind this.

### OmniSharp-node-client
- Added custom endpoints to accommodate OmniSharp features that the language server protocol doesn't support.

### OmniSharp-vscode
- Updates? Progress? Goals?
- Contributors outside Microsoft?
  - Are now being accepted!
- Use OmniSharp-node-client?
  - On the table as something to do in the future.

### OmniSharp-roslyn
- What else?

### OmniSharp-scaffolding
- _Any information / updates?_

### OmniSharp-brackets
- _Any information / updates?_

### OmniSharp-sublime
- _Any information / updates?_

### OmniSharp-emacs
- _Any information / updates?_

  cc @ianbattersby
### Additional agenda items?

Either update the issue, or add them in the comments below!

cc @OmniSharp/all

**Comment by willl** [comment]
Believe OmniSharp-emacs has had a [request out for new maintainers](https://github.com/OmniSharp/omnisharp-emacs/issues/265) with @sp3ctum announcing that he won't be maintaining it any longer. @razzmatazz has put his hand up as one, so let's try to include him in this ?

@razzmatazz, feel free to join the [omnisharp slack team](https://github.com/OmniSharp/omnisharp-roslyn/wiki).

**Comment by mikavilpas** [comment]
Hello, regarding omnisharp-emacs, this is indeed correct. We have been
going over the codebase and development environment of omnisharp-emacs in
one Skype session, and will do at least one more.

As for the future, we have agreed I will hang around for questions, the
idea being I won't have the main responsibility of maintaining. No specific
timeline set down yet.

I would like to know more about policies regarding the onboarding of new
members to the Omnisharp organization on GitHub. There used to be some kind
of NDA stuff I think, but does anyone know what the situation is today?

Mika

**Comment by ianbattersby** [comment]
@david-driscoll 

Just to confirm I have nothing new further to the minor development I did late in 2015 to enable multiple solutions/projects with Prodigy, further Spacemacs integration, and the starting of a better incremental-change mechanism (taking inspiration from undo-tree). 

Interestingly my work now brings me back into being able to use emacs/omnisharp on a daily basis so I am _very_ keen to see it progress and not stall, so on hand to lend a hand as required.

**Comment by filipw** [comment]
@david-driscoll you can add a separate "node" into the agenda about CSX support

A lot of activity happened around that space since last meeting:
 - we moved off scriptcs and into standard Roslyn scripting
 - alignment with CSI.exe
 - support for .NET Core scripting

On a side note, while this is not specific OmniSharp, I've also been working on bringing first class debugging experience into Roslyn for CSX (see https://github.com/dotnet/roslyn/pull/16489), which I hope will pave the way for nice debugging experience for scripting in VS Code.

**Comment by DustinCampbell** [comment]
@david-driscoll: Here are some potential topics...

* Using Mono as a runtime rather than CoreCLR
* Moving OmniSharp *back* to csproj from project.json
* New owners for projects that haven't seen much movement in awhile? Which projects are dead? Should we put out a call?
* Updating the OmniSharp website (http://www.omnisharp.net)
* Time to clean up the OmniSharp organization? Many members have moved on.
* New repo for the C# TextMate grammar (https://github.com/dotnet/csharp-tmLanguage)
* New Roslyn APIs coming after VS 2017 ships ([Quick Info](https://github.com/dotnet/roslyn/pull/13623), [Classification](https://github.com/dotnet/roslyn/pull/13741), [Signature Help](https://github.com/dotnet/roslyn/pull/13962))

@sp3ctum:

> I would like to know more about policies regarding the onboarding of new
members to the Omnisharp organization on GitHub. There used to be some kind
of NDA stuff I think, but does anyone know what the situation is today?

NDA issues are long gone. I believe that was from the days before ASP.NET Core was announced. Most discussion happens in the open on Slack these days anyway.

**Comment by ianbattersby** [comment]
Just to +1 @DustinCampbell suggestion on _"Moving OmniSharp back to csproj from project.json"_ as this is causing us a lot of friction at the moment, and with the emergence of MSBuild vs Desktop-MSBuild I wonder if there is a lot of ground to cover here? Also if _"Using Mono as a runtime rather than CoreCLR"_ is a serious prospect I'd be keen to express some concerns around this too 😨

**Comment by david-driscoll** [comment]
To note I've seen @DustinCampbell 's  prototype to use mono, and it was pretty cool.  We'll discuss on the call.  Though the underlying solution would use an embedded mono, not requiring mono to be installed on the users system.

**Comment by david-driscoll** [comment]
I have sent out calendar invites.

If you didn't get one, and want one, send me an email david.driscoll@gmail.com
If you did get one, and don't want it, send me a note and I'll remove you from future emails!

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
I'll be late (family reason). Will catch you through mail or PM asap.

**Comment by damieng** [comment]
I'm interesting in attending if that's okay.

**Comment by david-driscoll** [comment]
Sent invites to those that I can find emails.  You don't need to be on the invite list to join of course, it's just to make sure you have a reminder before hand (because I always need one!)

**Comment by DustinCampbell** [comment]
Please attend @damieng!

**Comment by ianbattersby** [comment]
Sincerely apologies to all but I now have a work conflict in my diary and likely won't be able to attend (the joys of working largely with a US-based team means I'm more often than not unavailable in the evenings opposed to mornings). I'm joining @sp3ctum and others for an emacs-related call on Sunday so will likely catchup with any meeting gossip then :+1:

cc @david-driscoll

**Comment by david-driscoll** [comment]
FYI looks like the skype meeting has expired... we're currently figuring out another one to use and will post those details here shortly.

**Comment by shmuelie** [comment]
@david-driscoll the S4B link isn't working 👎 

> FYI looks like the skype meeting has expired... we're currently figuring out another one to use and will post those details here shortly.

Guess I was too fast 👍

**Comment by david-driscoll** [comment]
Link for todays meeting https://meet.lync.com/pulsebridge/dmccaffery/21LHEHPV

**Comment by sayedihashimi** [comment]
Sorry I can't make it today. I have a meeting every thursday at this time.

**Comment by david-driscoll** [comment]
Notes:

David
* To help get atom-languageclient up and running for @damieng .

Fillip
* Overview of csx / csi.

Dustin
* Overview of MSBuild / Mono as a runtime host for OmniSharp
* New Textmate Grammar is Awesome!

Website
* David to look at updating or adding issues for the website
  * slack instead of jabber
  * update members

Aspnet-Generator
* Working with sayed to figure out what the default templates should be.


Projects needing owners:
* Brackets
* Emacs (work in progress)
* Sublime
* Vim

.NET Foundation
* Look at adopting
