### ISSUE TITLE
format linq

### ISSUE THREAD

**Issue by android272** [OmniSharp/OmniSharp#26]
Sorry if this is not the place for issues like this. If it is not I can post it somewhere else. I really would like to customize how OmniSharp formats linq.

Right now if I format this code using OmniSharp:
```
list.AddRange(
            from Node node in Graph.StartNode.Where(node => node is StartNode)
            where node.token != null
            let token = new Token(node.token)
            select token
);
```

I get this:
```
list.AddRange(
            from Node node in Graph.StartNode.Where(node => node is StartNode) where node.token != null
            let token = new Token(node.token)
            select token
);
```

I want the "from", "where", "let", "select" keywords on new lines but if I add multiple forms or wheres they get squashed together.

**Comment by filipw** [comment]
this is not the place indeed, that's why it was missed (this is a repo for organizational issues only).
However, to answer your question - this is not supported. OmniSharp uses Roslyn (https://github.com/dotnet/roslyn) to format the code, so if you'd like this to be supported, it would have to be added there first.
